function BW_out = filterRegionsLionsOne(BW_in,idx)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 18-Mar-2023
%---------------------------------------------------------

BW_out = BW_in;

if ((idx >= 500) && (idx <= 507))
    BW_out = bwpropfilt(BW_out,'Area',[28000, Inf]);

elseif ((idx == 597) || (idx == 569))
    BW_out = bwpropfilt(BW_out,'Area',[37000, Inf]);
else
% Filter image based on image properties.
    BW_out = bwpropfilt(BW_out,'Area',[33000, Inf]);
end
