function BW_out = filterRegionsLions(BW_in,idx)
%filterRegions Filter BW image using auto-generated code from imageRegionAnalyzer app.

% Auto-generated by imageRegionAnalyzer app on 18-Mar-2023
%---------------------------------------------------------

BW_out = BW_in;

% Filter image based on image properties.
if (((idx >= 108) && (idx <= 117)) || ((idx >= 222) && (idx <= 229))|| ((idx >= 485) && (idx <= 632)) || ((idx >= 55) && (idx <= 56)) || ((idx >= 59) && (idx <= 60)))
    BW_out = bwpropfilt(BW_out,'Area',[20000 + eps(20000), Inf]);

else 
    BW_out = bwpropfilt(BW_out,'Area',[10500 + eps(10500), Inf]);
end
