function [BW,maskedImage] = segmentImageLionsFirst(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 18-Mar-2023
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.

% Threshold image - global threshold
BW = imbinarize(im2gray(RGB));

% Fill holes
BW = imfill(BW, 'holes');

% Dilate mask with line
length = 7.000000;
angle = 0.000000;
se = strel('line', length, angle);
BW = imdilate(BW, se);

% Erode mask with square
width = 7;
se = strel('square', width);
BW = imerode(BW, se);

% Fill holes
BW = imfill(BW, 'holes');

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

