function [BW,maskedImage] = segmentImageThresholded(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Mar-2023
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.

% Threshold image - manual threshold
BW = im2gray(RGB) > 0;

% Close mask with default
radius = 2;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Erode mask with line
length = 6.000000;
angle = 0.000000;
se = strel('line', length, angle);
BW = imerode(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

