function [BW,maskedImage] = segmentImagetestMask(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Mar-2023
%----------------------------------------------------


% Threshold image - global threshold
BW = imbinarize(im2gray(X));

% Open mask with disk
radius = 2;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Dilate mask with disk
radius = 30;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Open mask with disk
radius = 32;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imopen(BW, se);

% Close mask with disk
radius = 80;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Close mask with rectangle
dimensions = [200 500];
se = strel('rectangle', dimensions);
BW = imclose(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

