function [BW,maskedImage] = segmentImageTurtle(RGB)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(RGB) segments image RGB using
%  auto-generated code from the Image Segmenter app. The final segmentation
%  is returned in BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 16-Mar-2023
%----------------------------------------------------


% Convert RGB image into L*a*b* color space.

% Threshold image - manual threshold
BW = im2gray(RGB) > 0;

% Fill holes
BW = imfill(BW, 'holes');

% Close mask with disk
radius = 6;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Erode mask with square
width = 29;
se = strel('square', width);
BW = imerode(BW, se);

% Create masked image.
maskedImage = RGB;
maskedImage(repmat(~BW,[1 1 3])) = 0;
end

